# Workflow for deploying the website

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: 

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@034294ac9150f471c8dd554f05f0685312e7f7bd # renovate: tag=v1.66.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Setup Java
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          java-version: 16
          distribution: temurin
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install xmlstarlet jq curl
          gem install jekyll bundler

      - name: Update website
        run: |
          WORKDIR="$HOME"/tmp
          mkdir "$WORKDIR"

          bash .github/deploy_website.sh "$WORKDIR" "github-actions[bot]" ${{ secrets.GITHUB_TOKEN }}
